version: "3.9"
services:
  app:
    build: .
    environment:
      - WORKERS=2
      - HF_HOME=/models
    volumes:
      - hf-cache:/models
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ui:/usr/share/nginx/html:ro

volumes:
  hf-cache:
